name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: make install
      - name: Lint
        run: make lint